import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { COMPANY, companyTelLine } from "./company";
import { formatDate } from "./format";
import type { PartyLedger } from "./accounting";
import { VOUCHER_TITLES, type VoucherPayload } from "./voucher";

export type { VoucherPayload } from "./voucher";

/** Shared business header: logo, name, address, phone. */
function drawCompanyHeader(doc: jsPDF, title: string) {
  doc.setFillColor(15, 28, 63);
  doc.rect(0, 0, 210, 36, "F");

  const logo = typeof window === "undefined" ? null : new Image();
  if (logo) {
    logo.src = COMPANY.logo;
  }

  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text(COMPANY.name, 14, 14);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.text(COMPANY.address, 14, 20);
  doc.text(`Tel: ${companyTelLine()}`, 14, 25);
  doc.text(`Email: ${COMPANY.email}`, 14, 30);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text(title, 140, 30);

  if (logo?.complete) {
    try {
      doc.addImage(logo, "JPEG", 168, 4, 28, 28, undefined, "FAST");
    } catch {
      /* logo is optional */
    }
  }
}

export function generateVoucherPDF(payload: VoucherPayload) {
  const doc = new jsPDF();
  drawCompanyHeader(doc, VOUCHER_TITLES[payload.kind]);

  doc.setTextColor(30, 41, 59);
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text(`Customer: ${payload.customerName}`, 14, 46);
  doc.setFontSize(9);
  doc.text(`Booking: ${payload.bookingId}`, 14, 52);

  autoTable(doc, {
    startY: 56,
    head: [["Field", "Details"]],
    body: payload.lines.map((l) => [l.label, l.value]),
    theme: "grid",
    headStyles: { fillColor: [37, 99, 235] },
    styles: { fontSize: 9 },
  });

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const finalY = (doc as any).lastAutoTable?.finalY || 100;
  if (payload.amount) {
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text(`Amount: ${payload.amount}`, 14, finalY + 10);
  }
  if (payload.note) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.text(payload.note, 14, finalY + (payload.amount ? 18 : 12));
  }

  doc.setFontSize(7);
  doc.setTextColor(100);
  doc.text(`${COMPANY.name} · ${COMPANY.email}`, 14, 285);

  doc.save(`${payload.kind}-${payload.bookingId}.pdf`);
}

/**
 * Party statement (debit / credit + running balance) exported as a PDF that
 * can be shared directly with the client or supplier.
 */
export function generateLedgerPDF(
  ledger: PartyLedger,
  from: string,
  to: string,
  money = (n: number) => `PKR ${n.toLocaleString("en-PK")}`
) {
  const doc = new jsPDF();
  drawCompanyHeader(doc, "Account Statement");

  doc.setTextColor(30, 41, 59);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(12);
  doc.text(`${ledger.partyType}: ${ledger.partyName}`, 14, 46);
  doc.setFontSize(10);
  const periodLine = `Period: ${from ? formatDate(from) : "Beginning"} — ${to ? formatDate(to) : "Today"}`;
  doc.text(periodLine, 14, 52);
  doc.text(`Opening Balance: ${money(ledger.opening)}`, 14, 58);

  const body = ledger.rows.map((r, i) => [
    String(i + 1),
    formatDate(r.date),
    r.ref,
    r.description,
    r.debit ? money(r.debit) : "—",
    r.credit ? money(r.credit) : "—",
    money(r.balance),
  ]);

  autoTable(doc, {
    startY: 64,
    head: [["#", "Date", "Ref", "Particulars", "Debit", "Credit", "Balance"]],
    body,
    theme: "grid",
    headStyles: { fillColor: [15, 28, 63] },
    styles: { fontSize: 8 },
    columnStyles: {
      0: { cellWidth: 8 },
      1: { cellWidth: 22 },
      4: { halign: "right" },
      5: { halign: "right" },
      6: { halign: "right" },
    },
  });

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const finalY = (doc as any).lastAutoTable?.finalY || 150;
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text(`Closing Balance: ${money(ledger.closing)}`, 14, finalY + 12);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(100);
  doc.text(`Generated by ${COMPANY.name}.`, 14, finalY + 20);

  const safe = ledger.partyName.replace(/[^a-z0-9]+/gi, "-").toLowerCase();
  doc.save(`statement-${safe}-${from || "all"}-${to || "today"}.pdf`);
}
